"""Add AttentionItem table

Revision ID: 7a08fe4c32ce
Revises: f9223dc58508
Create Date: 2026-08-12 12:42:10.594181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a08fe4c32ce'
down_revision: Union[str, None] = 'f9223dc58508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attention_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('idle_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attention_items_session_id'), 'attention_items', ['session_id'], unique=False)
    op.create_index(op.f('ix_attention_items_urgency_score'), 'attention_items', ['urgency_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attention_items_urgency_score'), table_name='attention_items')
    op.drop_index(op.f('ix_attention_items_session_id'), table_name='attention_items')
    op.drop_table('attention_items')
    # ### end Alembic commands ###