"""add digest_entry table

Revision ID: 7ec526e3de27
Revises: e6b76e0fc9f4
Create Date: 2026-08-12 15:16:12.346271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec526e3de27'
down_revision: Union[str, None] = 'e6b76e0fc9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest_entries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pr_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digest_entries_pr_id'), 'digest_entries', ['pr_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_digest_entries_pr_id'), table_name='digest_entries')
    op.drop_table('digest_entries')
    # ### end Alembic commands ###